### ISSUE TITLE
Play games by using in-screen controller for mobile gaming

### ISSUE THREAD

**Issue by tintheanh** [andychase/gbajs2#14]
Suggest having in-screen controller using <button> for playing on mobile. We can create a new class to handle <button> controls just like keypad.js

**Comment by andychase** [comment]
Good idea! Might be the same as #7

**Comment by jriceart** [comment]
@tintheanh I've posted the GBA designs with on screen controller on a different issue board,  didn't know if you saw these yet

https://www.figma.com/file/azIaf5sIOT1Vj86lIui0El/GBA.js?node-id=0%3A1

**Comment by tintheanh** [comment]
@jriceart The UI looks great! If the front-end code is not yet implemented I can try to jump in and work on it.

**Comment by andychase** [comment]
Duplicate of #13
