### ISSUE TITLE
start bug 勇者斗恶龙怪兽仙境中文版.gba

### ISSUE THREAD

**Issue by anlei586** [andychase/gbajs2#19]
*Rom link removed*
gba.js:233 Uncaught Unimplemented software interrupt: 0xd
runFunc @ gba.js:233
setTimeout (async)
GameBoyAdvance.window.queueFrame @ gba.js:68
runFunc @ gba.js:225
setTimeout (async)
GameBoyAdvance.window.queueFrame @ gba.js:68
runFunc @ gba.js:225
setTimeout (async)
GameBoyAdvance.window.queueFrame @ gba.js:68
runStable @ gba.js:237
(anonymous) @ (index):130
reader.onload @ gba.js:126
load (async)
loadRomFromFile @ gba.js:123
run @ (index):122
onchange @ (index):372

**Comment by andychase** [comment]
Is this for a specific rom? The emulator doesn’t have full compatibility

**Comment by andychase** [comment]
Yeah in your link it says unimplemented. I am not aiming to improve the compatibility, the original author restarted because of the challenge of doing so. I would just use a more complete emulator if you need more compatibility.
