### ISSUE TITLE
How do you load a save file?

### ISSUE THREAD

**Issue by heavilyarmedporky** [andychase/gbajs2#23]
Whenever you open a ROM, the "Upload Savegame" button disappears. Whenever I use the button before I open a ROM, it does nothing. Also, are the saves meant to be downloaded with no file extension?

**Comment by andychase** [comment]
Huh yeah that sounds broken. I haven't tried downloading/loading savegames

**Comment by andychase** [comment]
Oops didn't mean to close

**Comment by towhare** [comment]
I found out that save can work,should save game in game, then download save data, the next time open it, u should upload save gata data first and then select the game rom.

**Comment by andychase** [comment]
Okay that's sounds right. Maybe the ticket should be rename to "improve save ui".

In personal projects I had implemented saving periodically to the browser memory. There's not a way to "save on tab close" so I had to just have it save through a timer.

**Comment by 1likegithub** [comment]
it didn't work even after i tried towhares method
