### ISSUE TITLE
How to preload ROMs and avoid selecting ROM

### ISSUE THREAD

**Issue by physics1024** [andychase/gbajs2#25]
I'm a private user.My school device use the browser that doesn't support local file browsing and downloading.Is there a method that can preload ROMs ?And can we use Cookie to save the game?

**Comment by andychase** [comment]
Yeah you would have to host the website yourself. One of the other tickets
has some sample code

**Comment by physics1024** [comment]
Should I use javascript? If so,can I use the code "new ActiveXObject(“Scripting.FileSystemObject”)"? I'm new to HTML so I'd appreciate it if you can give some advice. Many thanks!

**Comment by andychase** [comment]
Sorry I can't provide that level of technical support! I would recommend https://www.codementor.io/

**Comment by andychase** [comment]
See ticket https://github.com/andychase/gbajs2/issues/24 for similar code
