### ISSUE TITLE
Question about debugger and console

### ISSUE THREAD

**Issue by xxxdrewwerdxxx** [andychase/gbajs2#26]
What is the debugger and console? And how do you use it? Thank you!

**Comment by andychase** [comment]
`How it's currently implemented is you would have to go to `/debugger.html`... though I'm not sure it works in gbajs2. I think some "renderers" support it and others do not.

Hope this is helpful!

**Comment by andychase** [comment]
See https://github.com/andychase/gbajs2/issues/11
