### ISSUE TITLE
Mobile interface

### ISSUE THREAD

**Issue by andychase** [andychase/gbajs2#7]
There is a pretty good implementation of it here:

https://github.com/trentmercer/gameplayadvanced

I have been working with some of these changes locally. I do think the style of it could be improved. Also if there could be a way of allowing someone to drag their finger to change which dpad input they are putting in (currently only taps work)

@trentmercer are you interested in trying to merge your changes in?

**Comment by trentmercer** [comment]
Would love to help out if I get some time this weekend

**Comment by andychase** [comment]
Duplicate of #13
